robot_board_offsets:
  x: 0.115
  y: 0.352
  z: 0.243

board_dimensions:
  x_increment: 0.0375
  y_increment: 0.0375

clock_locations:
  x_pos: 0.370
  y_pos: 0.110

robot_base:
  default_pan_angle: -3.1415

specific_joint_angles:
  home: "1 1 1 1 1 1"